### ISSUE TITLE
Does this project support bazel 5.2.0?

### ISSUE THREAD

**Issue by qiantanjingtao** [bazelbuild/rules_android_ndk#31]
When I use bazel 5.2.0, the warning is :
```bash
 " The major revision of the Android NDK referenced by android_ndk_repository rule 'androidndk' is 25. The major revisions supported by Bazel are [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]. Bazel will attempt to treat the NDK as if it was r21. This may cause compilation and linkage problems. Please download a supported NDK version.".
```
Any suggestion? Thanks.

**Comment by ahumesky** [comment]
Hi, it looks like you're using the "native" version (i.e. the non-Starlark version) of android_ndk_repository (https://bazel.build/reference/be/android#android_ndk_repository)

Are you loading the rules_android_ndk version (i.e. Starlark version) of android_ndk_repository like this?:
https://github.com/bazelbuild/rules_android_ndk#getting-started

**Comment by qiantanjingtao** [comment]
Thanks for reply.
What's the difference between WORKSPACE in your second url  and WORKSPACE in examples/basic ?
I've add the https://github.com/bazelbuild/rules_android_ndk#getting-started in the end of my project WORKSPACE, while
another error happend:

```bash
ERROR: /home/zhu/.cache/bazel/_bazel_zhu/bf5ae187c183939636c65d4e920e7dc3/external/local_config_cc/BUILD:47:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'arm64-v8a'
ERROR: /home/zhu/.cache/bazel/_bazel_zhu/bf5ae187c183939636c65d4e920e7dc3/external/local_config_cc/BUILD:47:19: Analysis of target '@local_config_cc//:toolchain' failed
```
Thanks again.

**Comment by ahumesky** [comment]
Ah, so is `avatar-sdk/Session:libsession.so` a `cc_binary`? If so, then other flags are needed, because only `android_binary` will use `--fat_apk_cpu` and `--android_crosstool_top`. You'll need to set `--cpu` and `--crosstool_top` (and maybe also set `--host_crosstool_top` to the default host toolchain). Is that was `--config=android_arm64` does?

**Comment by qiantanjingtao** [comment]
Yes, ```avatar-sdk/Session:libsession.so``` is a ```cc_binary```. 
And my project (mediapipe written by google) ```.bazelrc``` is as following:
```bash
# Android configs.
# Note: the documentation tells us to use @androidndk//:default_crosstool, but
# the automatic configuration transition uses //external:android/crosstool.
# Using it here works and spares us from having two different config_settings
# for Android.
build:android --crosstool_top=//external:android/crosstool
build:android --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
build:android --linkopt=-landroid
build:android --linkopt=-ldl
build:android --linkopt=-llog
build:android --linkopt=-lm
build:android --linkopt=-Wl,--gc-sections

build:android_arm --config=android
build:android_arm --cpu=armeabi-v7a
build:android_arm --fat_apk_cpu=armeabi-v7a

build:android_arm64 --config=android
build:android_arm64 --cpu=arm64-v8a
build:android_arm64 --fat_apk_cpu=arm64-v8a
``` 
So，your guess is exactly right.
I guess that some options(select which toolchain?) are also from my project(mediapipe) but not from the ```rules_android_ndk```. 
In other words,  ````rules_android_ndk``` don't work as expected.
Thanks.

**Comment by qiantanjingtao** [comment]
Thanks for reply.
I've tried all your suggestions and it also be in error.
The error is:
```bash
ERROR: /home/zhu/mediapipe/mediapipe/util/BUILD:77:11: no such target '@androidndk//:cpufeatures': target 'cpufeatures' not declared in package '' defined by /home/zhu/.cache/bazel/_bazel_zhu/bf5ae187c183939636c65d4e920e7dc3/external/androidndk/BUILD and referenced by '//mediapipe/util:cpu_util'
```
Thanks again.

**Comment by ahumesky** [comment]
The `cpufeatures` target that the native version of android_ndk_library was not added to the starlark version.
I added them with b718a4b96b392a2ed8e2585a350bfd6d1eaaedae and c76a94ff365cac3c4f9c218eca6195a9b662530b.

However, in the native version of android_ndk_library, the cpu features files would be included like
`#include "ndk/sources/android/cpufeatures/cpu-features.h"`, and with the way that the starlark ndk respository is laid out, it would be `#include "sources/android/cpufeatures/cpu-features.h"` in the starlark version. So mediapipe might not compile with the file path without the `ndk/` prefix. If it's possible to modify your local version of mediapipe temporarily, you could try that. If not, then mediapipe will need to be updated.

**Comment by ahumesky** [comment]
Looking through mediapipe's code with respect to my previous comment, and yeah, this import will fail with the starlark version of android_ndk_repository:

https://github.com/google/mediapipe/blob/6cdc6443b6a7ed662744e2a2ce2d58d9c83e6d6f/mediapipe/util/cpu_util.cc#L20

Probably the most straight forward thing to do would be to somehow make the starlark version of android_ndk_repository backwards compatible with the `ndk/` prefixed import paths...

**Comment by qiantanjingtao** [comment]
Thanks for reply. @ahumesky 
I have changed WORKSPACE to follow your latest commit https://github.com/bazelbuild/rules_android_ndk/commit/c76a94ff365cac3c4f9c218eca6195a9b662530b. The ```no such target '@androidndk//:cpufeatures' ``` has gone. Thanks for your work.
As you mentioned, the ```#include "ndk/sources/android/cpufeatures/cpu-features.h``` in ```Mediapipe``` need to be changed to ```#include "sources/android/cpufeatures/cpu-features.h"```.
After this changes, everything is ok in compilation step. however, linker complained about as following:
```bash
ld.lld: error: unable to find library -lpthread
```
I find that https://github.com/bazelbuild/rules_android_ndk/issues/5#issue-1360980880 has mentioned in point (6). I have modified configs following https://github.com/gflags/gflags/pull/321/commits/59fb6443a82b84c6b5971b2f45403c78727b7604
, but failed again.
My libraries in external directory are
![image](https://user-images.githubusercontent.com/26004389/212010507-b425c09a-6d68-45c2-9453-517620c52dfa.png)

Any suggestion will be help.
Thanks again.

**Comment by ahumesky** [comment]
With https://github.com/bazelbuild/rules_android_ndk/commit/44dcd014f4b126f8941c29ff1b25e1584bd3eb26 changing the include path in mediapipe shouldn't be necessary anymore. We'll have to followup on the pthread issue next week.

**Comment by qiantanjingtao** [comment]
Thanks for your work, @ahumesky 
Glad to hear you will start the pthread issue. 
Thanks again.

**Comment by ahumesky** [comment]
I see you found a workaround with https://github.com/bazelbuild/rules_android_ndk/issues/5#issuecomment-1385288459 glad you are unblocked.

I think `unable to find library -lpthread` is actually a symptom of this config_setting not working with the starlark version of android_ndk_repository:

https://github.com/tensorflow/tensorflow/blob/93905da81b2995eaba088b715c7d61dcbed51c31/tensorflow/tensorflow.bzl#L449

https://github.com/tensorflow/tensorflow/blob/a801af081952535b541852ad6ad96e0d536f2965/tensorflow/BUILD#L195

Tensorflow would need to use the new value of `@androidndk//:toolchain` instead of `//external:android/crosstool`.

Putting a `bind` in your top-level workspace file may work as a workaround:

`bind("android/crosstool", "@androidndk//:toolchain")`

If that doesn't work on its own, you might need to set `--crosstool_top` as well:

`--crosstool_top=//external:android/crosstool`

**Comment by keith** [comment]
I hit the pthread issue outside of tensorflow so I imagine it's other places too. Seems like either way we should update that config setting in tensorflow to use the OS from the platforms repo

**Comment by qiantanjingtao** [comment]
Hi, @ahumesky , Sorry for delay.
I have add the ``` ind(name="//external:android/crosstool", actual="@androidndk//:toolchain") ``` in my top-level WORKSPACE file, but it doesn't work.
I found that tensorflow has many ``` //external:android/crosstool ```,  my ``` grep ``` command outputs are
![image](https://user-images.githubusercontent.com/26004389/216310772-e000138b-c645-4101-b903-0e23fa7587fb.png)
Should I modify all of these config ? Furthermore，Should I modify all ```//external:android/crosstool``` in ``` external ``` directory ?
By the way, what is the meaning of  ``` catch-22 ``` ?
Thanks.

**Comment by ahumesky** [comment]
You might try
```
bind(
    name = "android/crosstool",
    actual = "@androidndk//:toolchain",
)
```

I don't think that the "//external:" is necessary.

By the way, do you have a directory called `external` at the top-level of your workspace? Bazel treats `external` differently because of the (unfortunate) binding schemes with `bind` (we would actually like to get rid of `bind` one day...).  See this issue for more details: https://github.com/bazelbuild/bazel/issues/4508

If the bind above doesn't work, then probably the most expedient solution is to change the config_settings in your local version of tensorflow to use `@androidndk//:toolchain` instead of `//external:android/crosstool` until this is sorted out with tensorflow. This is not so great because it makes upgrading tensorflow harder, and requires that you vendor the source code (which you might already be doing), but again it might be the most expedient.

Sorry for "catch-22" -- I should be a little more precise. "Catch-22" is when you have a problem and the solutions for it mutually conflict. So using `--crosstool_top=//external:android/crosstool` with the `bind` might fix one set of config_settings, but could cause other config_settings to break, so it's a "catch-22".

**Comment by qiantanjingtao** [comment]
Hi， @ahumesky 
The ``` bind ``` mentioned above doesn't work all the time. So i tried to change  the ``` //external:android/crosstool ``` in my local version.
Sorry, The ``` external ``` is not my customized directory but is generated by bazel (a cache directory), which location is ``` ~/.cache/bazel/_bazel_zhu/bf5ae187c183939636c65d4e920e7dc3/external ``` in my machine. 

I have moved all  ``` //external:android/crosstool ``` to ``` @androidndk//:toolchain ``` located in above ```external``` directory manually. Finally, it works well. By the way, is there an update for above change when tensorflow will upgrade in the future? 
 Because it is not an elegant way.
Thanks for explaining the ``` Catch-22 ```.
Thanks again.

**Comment by qiantanjingtao** [comment]
Hi, @ahumesky 
I have changed ``` api_level ``` value at the top-level of my WORKSPACE. 
I found that ``` android_ndk_repository(name = "androidndk", api_level=26) ``` is valid, but ``` android_ndk_repository(name = "androidndk", api_level=25) ``` is error.
Is 26 the smallest number of api level ?
Thanks.

**Comment by ahumesky** [comment]
Can you share what the error is?

**Comment by qiantanjingtao** [comment]
> Hi, @ahumesky I have changed `api_level` value at the top-level of my WORKSPACE. I found that `android_ndk_repository(name = "androidndk", api_level=26)` is valid, but `android_ndk_repository(name = "androidndk", api_level=25)` is error. Is 26 the smallest number of api level ? Thanks.

Hi, @ahumesky 
There is no error but a phenomenon when I set ```api_level=25```.
I have no question about this issue. I close this issue now. 
Thanks a lot. 
Best wishes.
